### ISSUE TITLE
Improve visibility of contribution guidelines

### ISSUE THREAD

**Issue by aurorarossi** [slimgroup/InvertibleNetworks.jl#106]
Ref openjournals/joss-reviews#6554 
A requirement of JOSS is to have clear guidelines for third parties who wish to:
  - Contribute to the software
 - Report issues or problems with the software

  - Seek support

Namely, the `CONTRIBUTING.md` file is missing.
Here are some examples:
- https://github.com/JuliaGraphs/Graphs.jl/blob/master/CONTRIBUTING.md
- https://github.com/FluxML/Flux.jl/blob/master/CONTRIBUTING.md
- https://github.com/JuliaGraphs/GraphsOptim.jl/blob/main/CONTRIBUTING.md

**Comment by mloubout** [comment]
We do have a 

- contributing
- code of conduct

These we have set up organization-wide. You can see it in the bottom corner when opening an issue and PR where it's supposed to be.

<img width="1303" alt="image" src="https://github.com/slimgroup/InvertibleNetworks.jl/assets/5702350/69293d34-a925-4167-9a10-c62a301805bf">

**Comment by aurorarossi** [comment]
Ah ok, I did not see it. I saw the code of conduct, which is visible near the README, but the contributing file is not as visible. It is ok that it is the same as the organization one, but just looking at the repository, if someone wants to open a PR and has not opened an issue, they will miss that information. I think you could create a section in the README that points this out.

**Comment by rafaelorozco** [comment]
[Update README.md w/ contribution guide](https://github.com/slimgroup/InvertibleNetworks.jl/commit/cf19a4f3411fa1b5fd83c08b7fd465f81a6e9a95)

Added a contribution guide to the readme. Hope you agree this is good!

**Comment by aurorarossi** [comment]
Yes, I close the issue.
