### ISSUE TITLE
JOLI

### ISSUE THREAD

**Issue by clive-g-brown** [slimgroup/InvertibleNetworks.jl#25]
Hi - Im getting this on installation

Resolving package versions...
ERROR: Unsatisfiable requirements detected for package JOLI [bb331ad6]:
 JOLI [bb331ad6] log:
 ├─JOLI [bb331ad6] has no known versions!
 └─restricted to versions * by InvertibleNetworks [b7115f24] — no versions left
   └─InvertibleNetworks [b7115f24] log:
     ├─possible versions are: 2.0.0 or uninstalled
     └─InvertibleNetworks [b7115f24] is fixed to version 2.0.0

**Comment by mloubout** [comment]
Hi

How did you install JOLI and InvertibleNetworks?
