### ISSUE TITLE
GPU support of InvertibleNetworks in julia 1.6.1

### ISSUE THREAD

**Issue by ryxchina** [slimgroup/InvertibleNetworks.jl#30]
Hi, I am trying to test the GPU support example for InvertibleNetworks in julia 1.6.1, but got errors. The error massages and package infomation is attached. Could someone help me with this? Thanks!
[Packages and error massages.txt](https://github.com/slimgroup/InvertibleNetworks.jl/files/6796951/Packages.and.error.massages.txt)

**Comment by mloubout** [comment]
This `parameters` error is a known issue with the recent CUDA.jl version and its dependencies. you can downgrade CUDA.jl for now (@alisiahkoohi you had this issue too right?)

**Comment by alisiahkoohi** [comment]
Yes I had. You could also explicitly install ExprTools@0.1.3 as suggested in https://discourse.julialang.org/t/help-needed-with-cuda/63923

**Comment by ryxchina** [comment]
> Yes I had. You could also explicitly install ExprTools@0.1.3 as suggested in https://discourse.julialang.org/t/help-needed-with-cuda/63923

Thanks, @alisiahkoohi and @mloubout , it works like a charm!
