### ISSUE TITLE
Conditionally load heavy dependencies

### ISSUE THREAD

**Issue by sethaxen** [slimgroup/InvertibleNetworks.jl#35]
Can any of the dependencies be conditionally loaded to make the package more lightweight as a dependency? e.g. is the Zygote dependency necessary for all usage, or does it only add compatibility with Zygote? If the latter, that code could be conditionally loaded with Requires.

**Comment by mloubout** [comment]
Thank you for the comment.

We tried to keep this package as minimal as possible but we will check if we have unnecessary dependencies.
